name: 02 - Workflow Events
on: workflow_dispatch
# on: 
#     push:
#     pull_request:
    # schedule:
    #     - cron: '* * * * *'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: | 
                echo "Event name: ${{ github.event_name }}."