name: 02 - Workflow Events
on: 
    push:
    schedule:
        - cron: '* * * * *'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: | 
                echo "Event name: ${{ github.event_name }}."